name: aufmass_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial_ble: ^0.4.3  # HIER GEÄNDERT: Unterstützt Classic & Gradle 9.3
  shared_preferences: ^2.2.0
  pdf: ^3.10.0
  printing: ^5.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
